### ISSUE TITLE
Multiple VS instances

### ISSUE THREAD

**Issue by brunojuliao** [VorTechS/VSMediaPlayerExtension#24]
1. opened one VS instance. Opened the control window. Started reproducing the content.

1.1. I opened a second VS instance. The control window was opened. It keeps saying "ordering content". I closed the window. When I tried to reopen it, I got the alert of multiple instances (that can be suppressed). My suggestion here is to check when control is loaded if there's already an instance open somewhere else. If yes, don't allow a second instance to be open.

1.2. I configured to suppress multiple instances warning. Closed the second VS instance. Open another VS instance. This time the window was not open. Then I went to View -> Other Windows -> "Visual Studio Media Player" and it opened fine another window (my first VS instance was still open and reproducing content) and started playing.

I think the suggestion on 1.1 fixes 1.2 as well.

**Comment by VorTechS** [comment]
The software already checks if the user control is instantiated.  The problem here is that when you close the toolwindow, but Visual Studio doesn't really close it.

So, that I remember when I come to fix this, we need to remove the locking file from AppData when the player window is closed using the WPF IsVisibleChanged event (and the option to stop media playback is enabled) so that the subsequent check in the second instance works as expected.

Great find @brunojuliao !

**Comment by VorTechS** [comment]
This was released and confirmed fixed in v1.7
